TDEditor_TD[0] = TextDrawCreate(249.2828, 129.2475, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[0], 144.9432, 9.0000);
TextDrawAlignment(TDEditor_TD[0], 1);
TextDrawColor(TDEditor_TD[0], -5963521);
TextDrawBackgroundColor(TDEditor_TD[0], 255);
TextDrawFont(TDEditor_TD[0], 4);
TextDrawSetProportional(TDEditor_TD[0], 0);
TextDrawSetShadow(TDEditor_TD[0], 0);

TDEditor_TD[1] = TextDrawCreate(241.2852, 126.2763, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[1], 16.0000, 19.0000);
TextDrawAlignment(TDEditor_TD[1], 1);
TextDrawColor(TDEditor_TD[1], -5963521);
TextDrawBackgroundColor(TDEditor_TD[1], 255);
TextDrawFont(TDEditor_TD[1], 4);
TextDrawSetProportional(TDEditor_TD[1], 0);
TextDrawSetShadow(TDEditor_TD[1], 0);

TDEditor_TD[2] = TextDrawCreate(385.9078, 126.1914, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[2], 16.0000, 19.0000);
TextDrawAlignment(TDEditor_TD[2], 1);
TextDrawColor(TDEditor_TD[2], -5963521);
TextDrawBackgroundColor(TDEditor_TD[2], 255);
TextDrawFont(TDEditor_TD[2], 4);
TextDrawSetProportional(TDEditor_TD[2], 0);
TextDrawSetShadow(TDEditor_TD[2], 0);

TDEditor_TD[3] = TextDrawCreate(243.9826, 135.5484, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[3], 155.2608, 9.0000);
TextDrawAlignment(TDEditor_TD[3], 1);
TextDrawColor(TDEditor_TD[3], -5963521);
TextDrawBackgroundColor(TDEditor_TD[3], 255);
TextDrawFont(TDEditor_TD[3], 4);
TextDrawSetProportional(TDEditor_TD[3], 0);
TextDrawSetShadow(TDEditor_TD[3], 0);

TDEditor_TD[4] = TextDrawCreate(243.9992, 144.2569, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[4], 155.0000, 121.6259);
TextDrawAlignment(TDEditor_TD[4], 1);
TextDrawColor(TDEditor_TD[4], -1);
TextDrawBackgroundColor(TDEditor_TD[4], 255);
TextDrawFont(TDEditor_TD[4], 4);
TextDrawSetProportional(TDEditor_TD[4], 0);
TextDrawSetShadow(TDEditor_TD[4], 0);

TDEditor_TD[5] = TextDrawCreate(259.2666, 151.1122, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[5], 125.0000, 18.0000);
TextDrawAlignment(TDEditor_TD[5], 1);
TextDrawColor(TDEditor_TD[5], -5963521);
TextDrawBackgroundColor(TDEditor_TD[5], 255);
TextDrawFont(TDEditor_TD[5], 4);
TextDrawSetProportional(TDEditor_TD[5], 0);
TextDrawSetShadow(TDEditor_TD[5], 0);

TDEditor_TD[6] = TextDrawCreate(260.2333, 152.4971, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[6], 123.0602, 15.2200);
TextDrawAlignment(TDEditor_TD[6], 1);
TextDrawColor(TDEditor_TD[6], -1);
TextDrawBackgroundColor(TDEditor_TD[6], 255);
TextDrawFont(TDEditor_TD[6], 4);
TextDrawSetProportional(TDEditor_TD[6], 0);
TextDrawSetShadow(TDEditor_TD[6], 0);

TDEditor_TD[7] = TextDrawCreate(259.2666, 178.9137, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[7], 125.0000, 18.0000);
TextDrawAlignment(TDEditor_TD[7], 1);
TextDrawColor(TDEditor_TD[7], -5963521);
TextDrawBackgroundColor(TDEditor_TD[7], 255);
TextDrawFont(TDEditor_TD[7], 4);
TextDrawSetProportional(TDEditor_TD[7], 0);
TextDrawSetShadow(TDEditor_TD[7], 0);

TDEditor_TD[8] = TextDrawCreate(259.2666, 200.2150, "LD_SPAC:white"); // пусто
TextDrawTextSize(TDEditor_TD[8], 125.0000, 18.0000);
TextDrawAlignment(TDEditor_TD[8], 1);
TextDrawColor(TDEditor_TD[8], -5963521);
TextDrawBackgroundColor(TDEditor_TD[8], 255);
TextDrawFont(TDEditor_TD[8], 4);
TextDrawSetProportional(TDEditor_TD[8], 0);
TextDrawSetShadow(TDEditor_TD[8], 0);

TDEditor_TD[9] = TextDrawCreate(297.8164, 216.7934, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[9], 47.0000, 47.0000);
TextDrawAlignment(TDEditor_TD[9], 1);
TextDrawColor(TDEditor_TD[9], -5963521);
TextDrawBackgroundColor(TDEditor_TD[9], 255);
TextDrawFont(TDEditor_TD[9], 4);
TextDrawSetProportional(TDEditor_TD[9], 0);
TextDrawSetShadow(TDEditor_TD[9], 0);

TDEditor_TD[10] = TextDrawCreate(300.8167, 219.6938, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[10], 41.0000, 41.0000);
TextDrawAlignment(TDEditor_TD[10], 1);
TextDrawColor(TDEditor_TD[10], -1);
TextDrawBackgroundColor(TDEditor_TD[10], 255);
TextDrawFont(TDEditor_TD[10], 4);
TextDrawSetProportional(TDEditor_TD[10], 0);
TextDrawSetShadow(TDEditor_TD[10], 0);
TextDrawSetSelectable(TDEditor_TD[10], true);

TDEditor_TD[11] = TextDrawCreate(294.9165, 129.6849, "PEВЕCПPAЙЕХ"); // пусто
TextDrawLetterSize(TDEditor_TD[11], 0.1875, 1.3285);
TextDrawAlignment(TDEditor_TD[11], 1);
TextDrawColor(TDEditor_TD[11], -1);
TextDrawBackgroundColor(TDEditor_TD[11], 255);
TextDrawFont(TDEditor_TD[11], 2);
TextDrawSetProportional(TDEditor_TD[11], 1);
TextDrawSetShadow(TDEditor_TD[11], 0);

TDEditor_TD[12] = TextDrawCreate(248.3332, 241.7639, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[12], 20.0000, 20.0000);
TextDrawAlignment(TDEditor_TD[12], 1);
TextDrawColor(TDEditor_TD[12], -5963521);
TextDrawBackgroundColor(TDEditor_TD[12], 255);
TextDrawFont(TDEditor_TD[12], 4);
TextDrawSetProportional(TDEditor_TD[12], 0);
TextDrawSetShadow(TDEditor_TD[12], 0);

TDEditor_TD[13] = TextDrawCreate(249.9998, 236.5786, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[13], 13.0000, 13.0000);
TextDrawAlignment(TDEditor_TD[13], 1);
TextDrawColor(TDEditor_TD[13], -5963521);
TextDrawBackgroundColor(TDEditor_TD[13], 255);
TextDrawFont(TDEditor_TD[13], 4);
TextDrawSetProportional(TDEditor_TD[13], 0);
TextDrawSetShadow(TDEditor_TD[13], 0);

TDEditor_TD[14] = TextDrawCreate(261.6665, 238.6528, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[14], 9.0000, 9.0000);
TextDrawAlignment(TDEditor_TD[14], 1);
TextDrawColor(TDEditor_TD[14], -5963521);
TextDrawBackgroundColor(TDEditor_TD[14], 255);
TextDrawFont(TDEditor_TD[14], 4);
TextDrawSetProportional(TDEditor_TD[14], 0);
TextDrawSetShadow(TDEditor_TD[14], 0);

TDEditor_TD[15] = TextDrawCreate(248.7498, 246.9491, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[15], 12.0000, 13.0000);
TextDrawAlignment(TDEditor_TD[15], 1);
TextDrawColor(TDEditor_TD[15], -1);
TextDrawBackgroundColor(TDEditor_TD[15], 255);
TextDrawFont(TDEditor_TD[15], 4);
TextDrawSetProportional(TDEditor_TD[15], 0);
TextDrawSetShadow(TDEditor_TD[15], 0);

TDEditor_TD[16] = TextDrawCreate(387.0830, 174.3564, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[16], 10.0000, 10.0000);
TextDrawAlignment(TDEditor_TD[16], 1);
TextDrawColor(TDEditor_TD[16], -5963521);
TextDrawBackgroundColor(TDEditor_TD[16], 255);
TextDrawFont(TDEditor_TD[16], 4);
TextDrawSetProportional(TDEditor_TD[16], 0);
TextDrawSetShadow(TDEditor_TD[16], 0);

TDEditor_TD[17] = TextDrawCreate(390.8330, 171.7637, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[17], 6.0000, 6.0000);
TextDrawAlignment(TDEditor_TD[17], 1);
TextDrawColor(TDEditor_TD[17], -5963521);
TextDrawBackgroundColor(TDEditor_TD[17], 255);
TextDrawFont(TDEditor_TD[17], 4);
TextDrawSetProportional(TDEditor_TD[17], 0);
TextDrawSetShadow(TDEditor_TD[17], 0);

TDEditor_TD[18] = TextDrawCreate(387.4996, 171.7637, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[18], 4.0000, 5.0000);
TextDrawAlignment(TDEditor_TD[18], 1);
TextDrawColor(TDEditor_TD[18], -5963521);
TextDrawBackgroundColor(TDEditor_TD[18], 255);
TextDrawFont(TDEditor_TD[18], 4);
TextDrawSetProportional(TDEditor_TD[18], 0);
TextDrawSetShadow(TDEditor_TD[18], 0);

TDEditor_TD[19] = TextDrawCreate(389.5827, 162.4305, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[19], 4.0000, 5.0000);
TextDrawAlignment(TDEditor_TD[19], 1);
TextDrawColor(TDEditor_TD[19], -5963521);
TextDrawBackgroundColor(TDEditor_TD[19], 255);
TextDrawFont(TDEditor_TD[19], 4);
TextDrawSetProportional(TDEditor_TD[19], 0);
TextDrawSetShadow(TDEditor_TD[19], 0);

TDEditor_TD[20] = TextDrawCreate(248.7496, 228.8010, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[20], 5.0000, 5.0000);
TextDrawAlignment(TDEditor_TD[20], 1);
TextDrawColor(TDEditor_TD[20], -5963521);
TextDrawBackgroundColor(TDEditor_TD[20], 255);
TextDrawFont(TDEditor_TD[20], 4);
TextDrawSetProportional(TDEditor_TD[20], 0);
TextDrawSetShadow(TDEditor_TD[20], 0);

TDEditor_TD[21] = TextDrawCreate(264.5827, 246.9491, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[21], 4.0000, 5.0000);
TextDrawAlignment(TDEditor_TD[21], 1);
TextDrawColor(TDEditor_TD[21], -5963521);
TextDrawBackgroundColor(TDEditor_TD[21], 255);
TextDrawFont(TDEditor_TD[21], 4);
TextDrawSetProportional(TDEditor_TD[21], 0);
TextDrawSetShadow(TDEditor_TD[21], 0);

TDEditor_TD[22] = TextDrawCreate(371.2492, 235.0233, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[22], 8.0000, 8.0000);
TextDrawAlignment(TDEditor_TD[22], 1);
TextDrawColor(TDEditor_TD[22], -5963521);
TextDrawBackgroundColor(TDEditor_TD[22], 255);
TextDrawFont(TDEditor_TD[22], 4);
TextDrawSetProportional(TDEditor_TD[22], 0);
TextDrawSetShadow(TDEditor_TD[22], 0);

TDEditor_TD[23] = TextDrawCreate(375.4158, 230.3566, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[23], 5.0000, 5.0000);
TextDrawAlignment(TDEditor_TD[23], 1);
TextDrawColor(TDEditor_TD[23], -5963521);
TextDrawBackgroundColor(TDEditor_TD[23], 255);
TextDrawFont(TDEditor_TD[23], 4);
TextDrawSetProportional(TDEditor_TD[23], 0);
TextDrawSetShadow(TDEditor_TD[23], 0);

TDEditor_TD[24] = TextDrawCreate(372.4992, 232.9491, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[24], 18.0000, 18.0000);
TextDrawAlignment(TDEditor_TD[24], 1);
TextDrawColor(TDEditor_TD[24], -5963521);
TextDrawBackgroundColor(TDEditor_TD[24], 255);
TextDrawFont(TDEditor_TD[24], 4);
TextDrawSetProportional(TDEditor_TD[24], 0);
TextDrawSetShadow(TDEditor_TD[24], 0);

TDEditor_TD[25] = TextDrawCreate(371.6658, 232.4308, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[25], 3.0000, 3.0000);
TextDrawAlignment(TDEditor_TD[25], 1);
TextDrawColor(TDEditor_TD[25], -5963521);
TextDrawBackgroundColor(TDEditor_TD[25], 255);
TextDrawFont(TDEditor_TD[25], 4);
TextDrawSetProportional(TDEditor_TD[25], 0);
TextDrawSetShadow(TDEditor_TD[25], 0);

TDEditor_TD[26] = TextDrawCreate(376.6658, 241.7641, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[26], 3.0000, 3.0000);
TextDrawAlignment(TDEditor_TD[26], 1);
TextDrawColor(TDEditor_TD[26], -1);
TextDrawBackgroundColor(TDEditor_TD[26], 255);
TextDrawFont(TDEditor_TD[26], 4);
TextDrawSetProportional(TDEditor_TD[26], 0);
TextDrawSetShadow(TDEditor_TD[26], 0);

TDEditor_TD[27] = TextDrawCreate(389.9992, 161.9122, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[27], 3.0000, 3.0000);
TextDrawAlignment(TDEditor_TD[27], 1);
TextDrawColor(TDEditor_TD[27], -1);
TextDrawBackgroundColor(TDEditor_TD[27], 255);
TextDrawFont(TDEditor_TD[27], 4);
TextDrawSetProportional(TDEditor_TD[27], 0);
TextDrawSetShadow(TDEditor_TD[27], 0);

TDEditor_TD[28] = TextDrawCreate(247.9158, 201.3197, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[28], 7.0000, 7.0000);
TextDrawAlignment(TDEditor_TD[28], 1);
TextDrawColor(TDEditor_TD[28], -5963521);
TextDrawBackgroundColor(TDEditor_TD[28], 255);
TextDrawFont(TDEditor_TD[28], 4);
TextDrawSetProportional(TDEditor_TD[28], 0);
TextDrawSetShadow(TDEditor_TD[28], 0);

TDEditor_TD[29] = TextDrawCreate(251.2492, 197.6900, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[29], 5.0000, 5.0000);
TextDrawAlignment(TDEditor_TD[29], 1);
TextDrawColor(TDEditor_TD[29], -5963521);
TextDrawBackgroundColor(TDEditor_TD[29], 255);
TextDrawFont(TDEditor_TD[29], 4);
TextDrawSetProportional(TDEditor_TD[29], 0);
TextDrawSetShadow(TDEditor_TD[29], 0);

TDEditor_TD[30] = TextDrawCreate(249.1658, 194.0605, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[30], 4.0000, 4.0000);
TextDrawAlignment(TDEditor_TD[30], 1);
TextDrawColor(TDEditor_TD[30], -5963521);
TextDrawBackgroundColor(TDEditor_TD[30], 255);
TextDrawFont(TDEditor_TD[30], 4);
TextDrawSetProportional(TDEditor_TD[30], 0);
TextDrawSetShadow(TDEditor_TD[30], 0);

TDEditor_TD[31] = TextDrawCreate(252.9158, 190.4308, "LD_BEAT:chit"); // пусто
TextDrawTextSize(TDEditor_TD[31], 3.0000, 3.0000);
TextDrawAlignment(TDEditor_TD[31], 1);
TextDrawColor(TDEditor_TD[31], -5963521);
TextDrawBackgroundColor(TDEditor_TD[31], 255);
TextDrawFont(TDEditor_TD[31], 4);
TextDrawSetProportional(TDEditor_TD[31], 0);
TextDrawSetShadow(TDEditor_TD[31], 0);

login_rp_TD[0] = TextDrawCreate(249.2828, 111.4477, "LD_SPAC:white"); // пусто
TextDrawTextSize(login_rp_TD[0], 144.9432, 9.0000);
TextDrawAlignment(login_rp_TD[0], 1);
TextDrawColor(login_rp_TD[0], -5963521);
TextDrawBackgroundColor(login_rp_TD[0], 255);
TextDrawFont(login_rp_TD[0], 4);
TextDrawSetProportional(login_rp_TD[0], 0);
TextDrawSetShadow(login_rp_TD[0], 0);

login_rp_TD[1] = TextDrawCreate(241.2852, 108.4766, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[1], 16.0000, 19.0000);
TextDrawAlignment(login_rp_TD[1], 1);
TextDrawColor(login_rp_TD[1], -5963521);
TextDrawBackgroundColor(login_rp_TD[1], 255);
TextDrawFont(login_rp_TD[1], 4);
TextDrawSetProportional(login_rp_TD[1], 0);
TextDrawSetShadow(login_rp_TD[1], 0);

login_rp_TD[2] = TextDrawCreate(385.9078, 108.3917, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[2], 16.0000, 19.0000);
TextDrawAlignment(login_rp_TD[2], 1);
TextDrawColor(login_rp_TD[2], -5963521);
TextDrawBackgroundColor(login_rp_TD[2], 255);
TextDrawFont(login_rp_TD[2], 4);
TextDrawSetProportional(login_rp_TD[2], 0);
TextDrawSetShadow(login_rp_TD[2], 0);

login_rp_TD[3] = TextDrawCreate(243.9826, 117.7481, "LD_SPAC:white"); // пусто
TextDrawTextSize(login_rp_TD[3], 155.2608, 9.0000);
TextDrawAlignment(login_rp_TD[3], 1);
TextDrawColor(login_rp_TD[3], -5963521);
TextDrawBackgroundColor(login_rp_TD[3], 255);
TextDrawFont(login_rp_TD[3], 4);
TextDrawSetProportional(login_rp_TD[3], 0);
TextDrawSetShadow(login_rp_TD[3], 0);

login_rp_TD[4] = TextDrawCreate(243.9992, 126.4560, "LD_SPAC:white"); // пусто
TextDrawTextSize(login_rp_TD[4], 155.0000, 101.5501);
TextDrawAlignment(login_rp_TD[4], 1);
TextDrawColor(login_rp_TD[4], -1);
TextDrawBackgroundColor(login_rp_TD[4], 255);
TextDrawFont(login_rp_TD[4], 4);
TextDrawSetProportional(login_rp_TD[4], 0);
TextDrawSetShadow(login_rp_TD[4], 0);

login_rp_TD[5] = TextDrawCreate(259.2666, 133.3112, "LD_SPAC:white"); // пусто
TextDrawTextSize(login_rp_TD[5], 125.0000, 18.0000);
TextDrawAlignment(login_rp_TD[5], 1);
TextDrawColor(login_rp_TD[5], -5963521);
TextDrawBackgroundColor(login_rp_TD[5], 255);
TextDrawFont(login_rp_TD[5], 4);
TextDrawSetProportional(login_rp_TD[5], 0);
TextDrawSetShadow(login_rp_TD[5], 0);

login_rp_TD[6] = TextDrawCreate(260.2333, 134.6961, "LD_SPAC:white"); // пусто
TextDrawTextSize(login_rp_TD[6], 123.0602, 15.2200);
TextDrawAlignment(login_rp_TD[6], 1);
TextDrawColor(login_rp_TD[6], -1);
TextDrawBackgroundColor(login_rp_TD[6], 255);
TextDrawFont(login_rp_TD[6], 4);
TextDrawSetProportional(login_rp_TD[6], 0);
TextDrawSetShadow(login_rp_TD[6], 0);

login_rp_TD[7] = TextDrawCreate(259.2666, 161.1127, "LD_SPAC:white"); // пусто
TextDrawTextSize(login_rp_TD[7], 125.0000, 18.0000);
TextDrawAlignment(login_rp_TD[7], 1);
TextDrawColor(login_rp_TD[7], -5963521);
TextDrawBackgroundColor(login_rp_TD[7], 255);
TextDrawFont(login_rp_TD[7], 4);
TextDrawSetProportional(login_rp_TD[7], 0);
TextDrawSetShadow(login_rp_TD[7], 0);

login_rp_TD[8] = TextDrawCreate(298.2330, 180.9913, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[8], 47.0000, 47.0000);
TextDrawAlignment(login_rp_TD[8], 1);
TextDrawColor(login_rp_TD[8], -5963521);
TextDrawBackgroundColor(login_rp_TD[8], 255);
TextDrawFont(login_rp_TD[8], 4);
TextDrawSetProportional(login_rp_TD[8], 0);
TextDrawSetShadow(login_rp_TD[8], 0);

login_rp_TD[9] = TextDrawCreate(301.2333, 183.8916, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[9], 41.0000, 41.0000);
TextDrawAlignment(login_rp_TD[9], 1);
TextDrawColor(login_rp_TD[9], -1);
TextDrawBackgroundColor(login_rp_TD[9], 255);
TextDrawFont(login_rp_TD[9], 4);
TextDrawSetProportional(login_rp_TD[9], 0);
TextDrawSetShadow(login_rp_TD[9], 0);
TextDrawSetSelectable(login_rp_TD[9], true);

login_rp_TD[10] = TextDrawCreate(292.4164, 111.8851, "AЛПOPЕИAЙЕХ"); // пусто
TextDrawLetterSize(login_rp_TD[10], 0.1875, 1.3285);
TextDrawAlignment(login_rp_TD[10], 1);
TextDrawColor(login_rp_TD[10], -1);
TextDrawBackgroundColor(login_rp_TD[10], 255);
TextDrawFont(login_rp_TD[10], 2);
TextDrawSetProportional(login_rp_TD[10], 1);
TextDrawSetShadow(login_rp_TD[10], 0);

login_rp_TD[11] = TextDrawCreate(244.4829, 203.8061, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[11], 23.0000, 25.0000);
TextDrawAlignment(login_rp_TD[11], 1);
TextDrawColor(login_rp_TD[11], -5963521);
TextDrawBackgroundColor(login_rp_TD[11], 255);
TextDrawFont(login_rp_TD[11], 4);
TextDrawSetProportional(login_rp_TD[11], 0);
TextDrawSetShadow(login_rp_TD[11], 0);

login_rp_TD[12] = TextDrawCreate(255.3163, 203.8061, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[12], 12.0000, 12.0000);
TextDrawAlignment(login_rp_TD[12], 1);
TextDrawColor(login_rp_TD[12], -5963521);
TextDrawBackgroundColor(login_rp_TD[12], 255);
TextDrawFont(login_rp_TD[12], 4);
TextDrawSetProportional(login_rp_TD[12], 0);
TextDrawSetShadow(login_rp_TD[12], 0);

login_rp_TD[13] = TextDrawCreate(262.8162, 201.2135, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[13], 7.0000, 7.0000);
TextDrawAlignment(login_rp_TD[13], 1);
TextDrawColor(login_rp_TD[13], -5963521);
TextDrawBackgroundColor(login_rp_TD[13], 255);
TextDrawFont(login_rp_TD[13], 4);
TextDrawSetProportional(login_rp_TD[13], 0);
TextDrawSetShadow(login_rp_TD[13], 0);

login_rp_TD[14] = TextDrawCreate(266.1495, 208.4728, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[14], 4.0000, 4.0000);
TextDrawAlignment(login_rp_TD[14], 1);
TextDrawColor(login_rp_TD[14], -5963521);
TextDrawBackgroundColor(login_rp_TD[14], 255);
TextDrawFont(login_rp_TD[14], 4);
TextDrawSetProportional(login_rp_TD[14], 0);
TextDrawSetShadow(login_rp_TD[14], 0);

login_rp_TD[15] = TextDrawCreate(252.8163, 206.9172, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[15], 15.0000, 17.0000);
TextDrawAlignment(login_rp_TD[15], 1);
TextDrawColor(login_rp_TD[15], -1);
TextDrawBackgroundColor(login_rp_TD[15], 255);
TextDrawFont(login_rp_TD[15], 4);
TextDrawSetProportional(login_rp_TD[15], 0);
TextDrawSetShadow(login_rp_TD[15], 0);

login_rp_TD[16] = TextDrawCreate(254.8996, 198.6209, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[16], 4.0000, 4.0000);
TextDrawAlignment(login_rp_TD[16], 1);
TextDrawColor(login_rp_TD[16], -5963521);
TextDrawBackgroundColor(login_rp_TD[16], 255);
TextDrawFont(login_rp_TD[16], 4);
TextDrawSetProportional(login_rp_TD[16], 0);
TextDrawSetShadow(login_rp_TD[16], 0);

login_rp_TD[17] = TextDrawCreate(253.2329, 201.7321, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[17], 6.0000, 6.0000);
TextDrawAlignment(login_rp_TD[17], 1);
TextDrawColor(login_rp_TD[17], -5963521);
TextDrawBackgroundColor(login_rp_TD[17], 255);
TextDrawFont(login_rp_TD[17], 4);
TextDrawSetProportional(login_rp_TD[17], 0);
TextDrawSetShadow(login_rp_TD[17], 0);

login_rp_TD[18] = TextDrawCreate(248.2329, 151.9543, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[18], 5.0000, 6.0000);
TextDrawAlignment(login_rp_TD[18], 1);
TextDrawColor(login_rp_TD[18], -5963521);
TextDrawBackgroundColor(login_rp_TD[18], 255);
TextDrawFont(login_rp_TD[18], 4);
TextDrawSetProportional(login_rp_TD[18], 0);
TextDrawSetShadow(login_rp_TD[18], 0);

login_rp_TD[19] = TextDrawCreate(251.1496, 156.6209, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[19], 4.0000, 5.0000);
TextDrawAlignment(login_rp_TD[19], 1);
TextDrawColor(login_rp_TD[19], -5963521);
TextDrawBackgroundColor(login_rp_TD[19], 255);
TextDrawFont(login_rp_TD[19], 4);
TextDrawSetProportional(login_rp_TD[19], 0);
TextDrawSetShadow(login_rp_TD[19], 0);

login_rp_TD[20] = TextDrawCreate(254.0662, 152.4728, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[20], 3.0000, 4.0000);
TextDrawAlignment(login_rp_TD[20], 1);
TextDrawColor(login_rp_TD[20], -5963521);
TextDrawBackgroundColor(login_rp_TD[20], 255);
TextDrawFont(login_rp_TD[20], 4);
TextDrawSetProportional(login_rp_TD[20], 0);
TextDrawSetShadow(login_rp_TD[20], 0);

login_rp_TD[21] = TextDrawCreate(334.0662, 188.7692, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[21], 6.0000, 6.0000);
TextDrawAlignment(login_rp_TD[21], 1);
TextDrawColor(login_rp_TD[21], -5963521);
TextDrawBackgroundColor(login_rp_TD[21], 255);
TextDrawFont(login_rp_TD[21], 4);
TextDrawSetProportional(login_rp_TD[21], 0);
TextDrawSetShadow(login_rp_TD[21], 0);

login_rp_TD[22] = TextDrawCreate(335.7329, 191.8803, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[22], 11.0000, 11.0000);
TextDrawAlignment(login_rp_TD[22], 1);
TextDrawColor(login_rp_TD[22], -5963521);
TextDrawBackgroundColor(login_rp_TD[22], 255);
TextDrawFont(login_rp_TD[22], 4);
TextDrawSetProportional(login_rp_TD[22], 0);
TextDrawSetShadow(login_rp_TD[22], 0);

login_rp_TD[23] = TextDrawCreate(342.8163, 201.2136, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[23], 5.0000, 5.0000);
TextDrawAlignment(login_rp_TD[23], 1);
TextDrawColor(login_rp_TD[23], -5963521);
TextDrawBackgroundColor(login_rp_TD[23], 255);
TextDrawFont(login_rp_TD[23], 4);
TextDrawSetProportional(login_rp_TD[23], 0);
TextDrawSetShadow(login_rp_TD[23], 0);

login_rp_TD[24] = TextDrawCreate(346.5662, 195.5099, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[24], 5.0000, 5.0000);
TextDrawAlignment(login_rp_TD[24], 1);
TextDrawColor(login_rp_TD[24], -5963521);
TextDrawBackgroundColor(login_rp_TD[24], 255);
TextDrawFont(login_rp_TD[24], 4);
TextDrawSetProportional(login_rp_TD[24], 0);
TextDrawSetShadow(login_rp_TD[24], 0);

login_rp_TD[25] = TextDrawCreate(347.3997, 202.2507, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[25], 9.0000, 9.0000);
TextDrawAlignment(login_rp_TD[25], 1);
TextDrawColor(login_rp_TD[25], -5963521);
TextDrawBackgroundColor(login_rp_TD[25], 255);
TextDrawFont(login_rp_TD[25], 4);
TextDrawSetProportional(login_rp_TD[25], 0);
TextDrawSetShadow(login_rp_TD[25], 0);

login_rp_TD[26] = TextDrawCreate(350.7331, 190.3247, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[26], 18.0000, 18.0000);
TextDrawAlignment(login_rp_TD[26], 1);
TextDrawColor(login_rp_TD[26], -5963521);
TextDrawBackgroundColor(login_rp_TD[26], 255);
TextDrawFont(login_rp_TD[26], 4);
TextDrawSetProportional(login_rp_TD[26], 0);
TextDrawSetShadow(login_rp_TD[26], 0);

login_rp_TD[27] = TextDrawCreate(362.8164, 202.7692, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[27], 10.0000, 10.0000);
TextDrawAlignment(login_rp_TD[27], 1);
TextDrawColor(login_rp_TD[27], -5963521);
TextDrawBackgroundColor(login_rp_TD[27], 255);
TextDrawFont(login_rp_TD[27], 4);
TextDrawSetProportional(login_rp_TD[27], 0);
TextDrawSetShadow(login_rp_TD[27], 0);

login_rp_TD[28] = TextDrawCreate(365.3164, 197.5839, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[28], 6.0000, 6.0000);
TextDrawAlignment(login_rp_TD[28], 1);
TextDrawColor(login_rp_TD[28], -5963521);
TextDrawBackgroundColor(login_rp_TD[28], 255);
TextDrawFont(login_rp_TD[28], 4);
TextDrawSetProportional(login_rp_TD[28], 0);
TextDrawSetShadow(login_rp_TD[28], 0);

login_rp_TD[29] = TextDrawCreate(370.3164, 201.7321, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[29], 4.0000, 4.0000);
TextDrawAlignment(login_rp_TD[29], 1);
TextDrawColor(login_rp_TD[29], -5963521);
TextDrawBackgroundColor(login_rp_TD[29], 255);
TextDrawFont(login_rp_TD[29], 4);
TextDrawSetProportional(login_rp_TD[29], 0);
TextDrawSetShadow(login_rp_TD[29], 0);

login_rp_TD[30] = TextDrawCreate(384.8997, 174.7692, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[30], 4.0000, 4.0000);
TextDrawAlignment(login_rp_TD[30], 1);
TextDrawColor(login_rp_TD[30], -5963521);
TextDrawBackgroundColor(login_rp_TD[30], 255);
TextDrawFont(login_rp_TD[30], 4);
TextDrawSetProportional(login_rp_TD[30], 0);
TextDrawSetShadow(login_rp_TD[30], 0);

login_rp_TD[31] = TextDrawCreate(383.2330, 153.5099, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[31], 8.0000, 8.0000);
TextDrawAlignment(login_rp_TD[31], 1);
TextDrawColor(login_rp_TD[31], -5963521);
TextDrawBackgroundColor(login_rp_TD[31], 255);
TextDrawFont(login_rp_TD[31], 4);
TextDrawSetProportional(login_rp_TD[31], 0);
TextDrawSetShadow(login_rp_TD[31], 0);

login_rp_TD[32] = TextDrawCreate(386.9830, 169.5840, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[32], 6.0000, 6.0000);
TextDrawAlignment(login_rp_TD[32], 1);
TextDrawColor(login_rp_TD[32], -5963521);
TextDrawBackgroundColor(login_rp_TD[32], 255);
TextDrawFont(login_rp_TD[32], 4);
TextDrawSetProportional(login_rp_TD[32], 0);
TextDrawSetShadow(login_rp_TD[32], 0);

login_rp_TD[33] = TextDrawCreate(384.0662, 164.9174, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[33], 6.0000, 6.0000);
TextDrawAlignment(login_rp_TD[33], 1);
TextDrawColor(login_rp_TD[33], -5963521);
TextDrawBackgroundColor(login_rp_TD[33], 255);
TextDrawFont(login_rp_TD[33], 4);
TextDrawSetProportional(login_rp_TD[33], 0);
TextDrawSetShadow(login_rp_TD[33], 0);

login_rp_TD[34] = TextDrawCreate(387.3995, 160.7693, "LD_BEAT:chit"); // пусто
TextDrawTextSize(login_rp_TD[34], 5.0000, 5.0000);
TextDrawAlignment(login_rp_TD[34], 1);
TextDrawColor(login_rp_TD[34], -5963521);
TextDrawBackgroundColor(login_rp_TD[34], 255);
TextDrawFont(login_rp_TD[34], 4);
TextDrawSetProportional(login_rp_TD[34], 0);
TextDrawSetShadow(login_rp_TD[34], 0);

TD_L[0] = TextDrawCreate(553.7501, 4.3702, "_n"); // пусто
TextDrawLetterSize(TD_L[0], 0.3720, 2.2118);
TextDrawAlignment(TD_L[0], 1);
TextDrawColor(TD_L[0], -1);
TextDrawBackgroundColor(TD_L[0], 255);
TextDrawFont(TD_L[0], 2);
TextDrawSetProportional(TD_L[0], 1);
TextDrawSetShadow(TD_L[0], 0);

TD_L[1] = TextDrawCreate(561.2501, 8.5185, "c"); // пусто
TextDrawLetterSize(TD_L[1], 0.3720, 2.2118);
TextDrawAlignment(TD_L[1], 1);
TextDrawColor(TD_L[1], -5963521);
TextDrawBackgroundColor(TD_L[1], 255);
TextDrawFont(TD_L[1], 2);
TextDrawSetProportional(TD_L[1], 1);
TextDrawSetShadow(TD_L[1], 0);

TD_L[2] = TextDrawCreate(565.8333, 11.6295, "Box"); // пусто
TextDrawLetterSize(TD_L[2], 0.0000, 0.8750);
TextDrawTextSize(TD_L[2], 565.0000, 0.0000);
TextDrawAlignment(TD_L[2], 1);
TextDrawColor(TD_L[2], -1);
TextDrawUseBox(TD_L[2], 1);
TextDrawBoxColor(TD_L[2], -1);
TextDrawBackgroundColor(TD_L[2], 255);
TextDrawFont(TD_L[2], 1);
TextDrawSetProportional(TD_L[2], 1);
TextDrawSetShadow(TD_L[2], 0);

TD_L[3] = TextDrawCreate(572.9165, 8.5185, "state"); // пусто
TextDrawLetterSize(TD_L[3], 0.2245, 1.8592);
TextDrawAlignment(TD_L[3], 1);
TextDrawColor(TD_L[3], -1);
TextDrawBackgroundColor(TD_L[3], 255);
TextDrawFont(TD_L[3], 2);
TextDrawSetProportional(TD_L[3], 1);
TextDrawSetShadow(TD_L[3], 0);

TD_L[4] = TextDrawCreate(565.8333, 11.6295, "Box"); // пусто
TextDrawLetterSize(TD_L[4], 0.0000, 0.8750);
TextDrawTextSize(TD_L[4], 565.0000, 0.0000);
TextDrawAlignment(TD_L[4], 1);
TextDrawColor(TD_L[4], -1);
TextDrawUseBox(TD_L[4], 1);
TextDrawBoxColor(TD_L[4], -1);
TextDrawBackgroundColor(TD_L[4], 255);
TextDrawFont(TD_L[4], 1);
TextDrawSetProportional(TD_L[4], 1);
TextDrawSetShadow(TD_L[4], 0);

farm_td[0] = TextDrawCreate(13.3332, 166.5343, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[0], 22.0000, 22.0000);
TextDrawAlignment(farm_td[0], 1);
TextDrawColor(farm_td[0], -5963521);
TextDrawBackgroundColor(farm_td[0], 255);
TextDrawFont(farm_td[0], 4);
TextDrawSetProportional(farm_td[0], 0);
TextDrawSetShadow(farm_td[0], 0);

farm_td[1] = TextDrawCreate(89.7324, 166.5343, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[1], 22.0000, 22.0000);
TextDrawAlignment(farm_td[1], 1);
TextDrawColor(farm_td[1], -5963521);
TextDrawBackgroundColor(farm_td[1], 255);
TextDrawFont(farm_td[1], 4);
TextDrawSetProportional(farm_td[1], 0);
TextDrawSetShadow(farm_td[1], 0);

farm_td[2] = TextDrawCreate(13.3332, 244.4391, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[2], 22.0000, 22.0000);
TextDrawAlignment(farm_td[2], 1);
TextDrawColor(farm_td[2], -5963521);
TextDrawBackgroundColor(farm_td[2], 255);
TextDrawFont(farm_td[2], 4);
TextDrawSetProportional(farm_td[2], 0);
TextDrawSetShadow(farm_td[2], 0);

farm_td[3] = TextDrawCreate(89.7324, 244.4391, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[3], 22.0000, 22.0000);
TextDrawAlignment(farm_td[3], 1);
TextDrawColor(farm_td[3], -5963521);
TextDrawBackgroundColor(farm_td[3], 255);
TextDrawFont(farm_td[3], 4);
TextDrawSetProportional(farm_td[3], 0);
TextDrawSetShadow(farm_td[3], 0);

farm_td[4] = TextDrawCreate(24.1833, 170.1638, "LD_SPAC:white"); // пусто
TextDrawTextSize(farm_td[4], 76.8171, 92.5504);
TextDrawAlignment(farm_td[4], 1);
TextDrawColor(farm_td[4], -5963521);
TextDrawBackgroundColor(farm_td[4], 255);
TextDrawFont(farm_td[4], 4);
TextDrawSetProportional(farm_td[4], 0);
TextDrawSetShadow(farm_td[4], 0);

farm_td[5] = TextDrawCreate(16.7000, 177.2601, "LD_SPAC:white"); // пусто
TextDrawTextSize(farm_td[5], 91.6003, 77.8774);
TextDrawAlignment(farm_td[5], 1);
TextDrawColor(farm_td[5], -1);
TextDrawBackgroundColor(farm_td[5], 255);
TextDrawFont(farm_td[5], 4);
TextDrawSetProportional(farm_td[5], 0);
TextDrawSetShadow(farm_td[5], 0);

farm_td[6] = TextDrawCreate(42.1500, 178.5924, "C¶a¶Ьc¶Ьka"); // пусто
TextDrawLetterSize(farm_td[6], 0.1524, 1.2048);
TextDrawAlignment(farm_td[6], 1);
TextDrawColor(farm_td[6], -5963521);
TextDrawBackgroundColor(farm_td[6], 255);
TextDrawFont(farm_td[6], 2);
TextDrawSetProportional(farm_td[6], 1);
TextDrawSetShadow(farm_td[6], 0);

farm_td[7] = TextDrawCreate(47.9999, 223.1074, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[7], 6.0000, 6.0000);
TextDrawAlignment(farm_td[7], 1);
TextDrawColor(farm_td[7], -5963521);
TextDrawBackgroundColor(farm_td[7], 255);
TextDrawFont(farm_td[7], 4);
TextDrawSetProportional(farm_td[7], 0);
TextDrawSetShadow(farm_td[7], 0);

farm_td[8] = TextDrawCreate(58.4996, 223.1074, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[8], 6.0000, 6.0000);
TextDrawAlignment(farm_td[8], 1);
TextDrawColor(farm_td[8], -5963521);
TextDrawBackgroundColor(farm_td[8], 255);
TextDrawFont(farm_td[8], 4);
TextDrawSetProportional(farm_td[8], 0);
TextDrawSetShadow(farm_td[8], 0);

farm_td[9] = TextDrawCreate(68.6996, 223.1074, "LD_BEAT:chit"); // пусто
TextDrawTextSize(farm_td[9], 6.0000, 6.0000);
TextDrawAlignment(farm_td[9], 1);
TextDrawColor(farm_td[9], -5963521);
TextDrawBackgroundColor(farm_td[9], 255);
TextDrawFont(farm_td[9], 4);
TextDrawSetProportional(farm_td[9], 0);
TextDrawSetShadow(farm_td[9], 0);
c_skin[0] = TextDrawCreate(203.3325, 345.2965, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[0], 229.0000, 46.0000);
TextDrawAlignment(c_skin[0], 1);
TextDrawColor(c_skin[0], -5963521);
TextDrawBackgroundColor(c_skin[0], 255);
TextDrawFont(c_skin[0], 4);
TextDrawSetProportional(c_skin[0], 0);
TextDrawSetShadow(c_skin[0], 0);

c_skin[1] = TextDrawCreate(203.3325, 347.3966, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[1], 229.0000, 41.9706);
TextDrawAlignment(c_skin[1], 1);
TextDrawColor(c_skin[1], -1);
TextDrawBackgroundColor(c_skin[1], 255);
TextDrawFont(c_skin[1], 4);
TextDrawSetProportional(c_skin[1], 0);
TextDrawSetShadow(c_skin[1], 0);

c_skin[2] = TextDrawCreate(204.6999, 351.1592, "Box"); // пусто
TextDrawLetterSize(c_skin[2], 0.0000, 3.8333);
TextDrawTextSize(c_skin[2], 257.5802, 0.0000);
TextDrawAlignment(c_skin[2], 1);
TextDrawColor(c_skin[2], -1);
TextDrawUseBox(c_skin[2], 1);
TextDrawBoxColor(c_skin[2], -5963521);
TextDrawBackgroundColor(c_skin[2], 255);
TextDrawFont(c_skin[2], 1);
TextDrawSetProportional(c_skin[2], 1);
TextDrawSetShadow(c_skin[2], 0);
TextDrawSetSelectable(c_skin[2], true);

c_skin[3] = TextDrawCreate(378.1105, 351.1592, "Box"); // пусто
TextDrawLetterSize(c_skin[3], 0.0000, 3.8333);
TextDrawTextSize(c_skin[3], 430.9908, 0.0000);
TextDrawAlignment(c_skin[3], 1);
TextDrawColor(c_skin[3], -1);
TextDrawUseBox(c_skin[3], 1);
TextDrawBoxColor(c_skin[3], -5963521);
TextDrawBackgroundColor(c_skin[3], 255);
TextDrawFont(c_skin[3], 1);
TextDrawSetProportional(c_skin[3], 1);
TextDrawSetShadow(c_skin[3], 0);
TextDrawSetSelectable(c_skin[3], true);

c_skin[4] = TextDrawCreate(260.3666, 351.5371, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[4], 4.0000, 33.5899);
TextDrawAlignment(c_skin[4], 1);
TextDrawColor(c_skin[4], -5963521);
TextDrawBackgroundColor(c_skin[4], 255);
TextDrawFont(c_skin[4], 4);
TextDrawSetProportional(c_skin[4], 0);
TextDrawSetShadow(c_skin[4], 0);

c_skin[5] = TextDrawCreate(371.3735, 351.5371, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[5], 4.0000, 33.5899);
TextDrawAlignment(c_skin[5], 1);
TextDrawColor(c_skin[5], -5963521);
TextDrawBackgroundColor(c_skin[5], 255);
TextDrawFont(c_skin[5], 4);
TextDrawSetProportional(c_skin[5], 0);
TextDrawSetShadow(c_skin[5], 0);

c_skin[6] = TextDrawCreate(366.0732, 354.3370, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[6], 4.0000, 28.2299);
TextDrawAlignment(c_skin[6], 1);
TextDrawColor(c_skin[6], -5963521);
TextDrawBackgroundColor(c_skin[6], 255);
TextDrawFont(c_skin[6], 4);
TextDrawSetProportional(c_skin[6], 0);
TextDrawSetShadow(c_skin[6], 0);

c_skin[7] = TextDrawCreate(265.5671, 354.3370, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[7], 4.0000, 28.2299);
TextDrawAlignment(c_skin[7], 1);
TextDrawColor(c_skin[7], -5963521);
TextDrawBackgroundColor(c_skin[7], 255);
TextDrawFont(c_skin[7], 4);
TextDrawSetProportional(c_skin[7], 0);
TextDrawSetShadow(c_skin[7], 0);

c_skin[8] = TextDrawCreate(272.6333, 351.5444, "LD_SPAC:white"); // пусто
TextDrawTextSize(c_skin[8], 90.8296, 33.6399);
TextDrawAlignment(c_skin[8], 1);
TextDrawColor(c_skin[8], -5963521);
TextDrawBackgroundColor(c_skin[8], 255);
TextDrawFont(c_skin[8], 4);
TextDrawSetProportional(c_skin[8], 0);
TextDrawSetShadow(c_skin[8], 0);

c_skin[9] = TextDrawCreate(221.6665, 355.1924, "<<"); // пусто
TextDrawLetterSize(c_skin[9], 0.3957, 2.7355);
TextDrawAlignment(c_skin[9], 1);
TextDrawColor(c_skin[9], -1);
TextDrawBackgroundColor(c_skin[9], 255);
TextDrawFont(c_skin[9], 3);
TextDrawSetProportional(c_skin[9], 1);
TextDrawSetShadow(c_skin[9], 0);
TextDrawSetSelectable(c_skin[9], true);

c_skin[10] = TextDrawCreate(397.8774, 355.1924, ">>"); // пусто
TextDrawLetterSize(c_skin[10], 0.3957, 2.7355);
TextDrawAlignment(c_skin[10], 1);
TextDrawColor(c_skin[10], -1);
TextDrawBackgroundColor(c_skin[10], 255);
TextDrawFont(c_skin[10], 3);
TextDrawSetProportional(c_skin[10], 1);
TextDrawSetShadow(c_skin[10], 0);
TextDrawSetSelectable(c_skin[10], true);

c_skin[11] = TextDrawCreate(299.5664, 342.7998, "O"); // пусто
TextDrawLetterSize(c_skin[11], 1.4782, 4.9443);
TextDrawAlignment(c_skin[11], 1);
TextDrawColor(c_skin[11], -1);
TextDrawBackgroundColor(c_skin[11], 255);
TextDrawFont(c_skin[11], 2);
TextDrawSetProportional(c_skin[11], 1);
TextDrawSetShadow(c_skin[11], 0);
TextDrawSetSelectable(c_skin[11], true);

p_alt[0] = TextDrawCreate(241.6665, 383.9260, "PRESS_:_ALT"); // пусто
TextDrawLetterSize(p_alt[0], 0.6453, 3.2177);
TextDrawAlignment(p_alt[0], 1);
TextDrawColor(p_alt[0], -1);
TextDrawSetOutline(p_alt[0], 1);
TextDrawBackgroundColor(p_alt[0], -5963521);
TextDrawFont(p_alt[0], 2);
TextDrawSetProportional(p_alt[0], 1);
TextDrawSetShadow(p_alt[0], 0);

td_speedometr[0] = TextDrawCreate(299.523834, 196.826660, "");
TextDrawLetterSize(td_speedometr[0], 0.400000, 1.600000);
TextDrawAlignment(td_speedometr[0], 2);
TextDrawColor(td_speedometr[0], -5963521);
TextDrawSetShadow(td_speedometr[0], 0);
TextDrawSetOutline(td_speedometr[0], 0);
TextDrawBackgroundColor(td_speedometr[0], 255);
TextDrawFont(td_speedometr[0], 0);
TextDrawSetProportional(td_speedometr[0], 1);
TextDrawSetShadow(td_speedometr[0], 0);

td_speedometr[1] = TextDrawCreate(290.000000, 190.000000, "");
TextDrawLetterSize(td_speedometr[1], 0.400000, 1.600000);
TextDrawAlignment(td_speedometr[1], 1);
TextDrawColor(td_speedometr[1], -1);
TextDrawSetShadow(td_speedometr[1], 0);
TextDrawSetOutline(td_speedometr[1], 0);
TextDrawBackgroundColor(td_speedometr[1], 255);
TextDrawFont(td_speedometr[1], 1);
TextDrawSetProportional(td_speedometr[1], 1);
TextDrawSetShadow(td_speedometr[1], 0);